use_frameworks!

platform :ios, '10.0'

target 'Learning_test_Example' do
  pod 'Learning_test', :path => '../'

  target 'Learning_test_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
